// Code generated by hotswap. DO NOT EDIT.

package {{.PackageName}}

import (
	"github.com/scoursen/hotswap"
	{{.PluginPkgName}} "{{.PluginPkgPath}}"
)

func init() {
	HotswapStaticPlugins["{{.PluginName}}"] = &hotswap.StaticPlugin {
		Name: "{{.PluginName}}",
		PluginFuncs: hotswap.NewPluginFuncs(
	{{- range .PluginFuncs}}
			{{.Expr}},
	{{- end}}
		),
	}
}
